name = "remoteadb-provision"
main = "worker.js"
compatibility_date = "2024-01-01"

# Set these via wrangler secret or GitHub Secrets
# CF_API_TOKEN, CF_ACCOUNT_ID, CF_ZONE_ID

[vars]
CF_DNS_SUFFIX = "676967.xyz"
